--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/SoftSell
build-by-default: true
branches:
- main
- poggit
projects:
  SoftSell:
    path: ""
    icon: "softsell.png"
...
