# Supported Database Provider
# - JSON
# - SQLite3
database-provider: JSON

# Supported Economy Provider
# - BedrockEconomy
# - EconomyAPI
economy-provider: BedrockEconomy

# Messages
# Tag's
# {revenue} -> Revenue Amount
with-message: true
sell-message: "+{revenue} balance"
